version: '3.7'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - suvidodb:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5430:5432
    expose: 
      - 5430
    command: -p 5430

  nginx:
    build: ./nginx
    ports:
      - 9002:9002
    depends_on:
      - backend
    volumes:
      - static_volume:/usr/share/backend/static
      - media_volume:/usr/share/backend/media

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  backend:
    build: .
    command: gunicorn server.wsgi:application --timeout 0 --workers 3 --reload --bind 0.0.0.0:9001
    ports:
      - 9001:9001
    volumes:
      - .:/usr/share/backend
      - static_volume:/usr/share/backend/static
      - media_volume:/usr/share/backend/media
    depends_on:
      - db
    expose:
      - 9001

volumes:
  suvidodb:
  static_volume:
  media_volume:

# networks: 
#   default: 
#     external: 
#       name: suvido-network