on:
  push:
    branches:
      - main

name: 🚀 Deploy project on server
jobs:
  deploy-application:
    runs-on: self-hosted

    name: 🎉 Deploying into server
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: Copying .env file for production
      run: echo ${{ secrets.PRODUCTION_ENV }} > .env

    # - name: Build docker
    #   run: docker-compose up --build -d

