on:
  push:
    branches:
      - main

name: 🚀 Deploy project on server
jobs:
  deploy-application:
    runs-on: self-hosted

    name: 🎉 Deploying into server
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Create .env file
      run: openssl enc -aes-256-cbc -iter 1259 -d -salt -in .env.prod.enc -out .env -k ${{ secrets.ENV_PRODUCTION_KEY }}

    - name: Build docker
      run: docker-compose up --build -d

    - name: Create user
      run: docker-compose run backend python manage.py createadminuser ${{ secrets.ADMIN_USER }}

